# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal7580-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a3xelte a5xelte a7xelte gvwifi gvlte j7elte j7xlte s5neolte,$(TARGET_DEVICE)),)

endif
